version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  web:
    restart: always
    build:
      context: ./education_project
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db

volumes:
  db: